databases:
  - name: CRM
    databaseName: CRM
    user: yomari
services:
  - type: web
    name: CRM
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: CRM
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false